### ISSUE TITLE
PHY really adapted?

### ISSUE THREAD

**Issue by davidzwa** [dverhaert/GNUradio-802.11ah#3]
I was wondering if the PHY layer is really adapted to 802.11ah.

It is stated [here](https://academica-e.unavarra.es/bitstream/handle/2454/22446/TFE_RemirezMoreno.pdf?sequence=1&isAllowed=y) on page 32 (pdf page 42) that:
- the OFDM carriers are changed.
- the modulation types & coding rates are changed.

You haven't committed the cc files of Bastian where you made these changes.

Also, looking at [Matlab PHY](https://nl.mathworks.com/help/wlan/ug/wlan-packet-structure.html) there seem to be quite structural differences between non-HT 802.11 versions and 802.11ah. It seems 802.11a/g/p aren't as compatible as we expected.
For example:
![image](https://user-images.githubusercontent.com/6005355/39703637-fbfa9160-5208-11e8-8280-4d62a7adc0e0.png)
versus 
![wlan_ppdu_format](https://user-images.githubusercontent.com/6005355/39757974-d239e170-52ce-11e8-89fa-d3f14d52a218.png)

**Comment by dverhaert** [comment]
Hi David,
- The current implementation does not change any carrier allocator range parameters. 
- I experimented with a higher coding rate and the new modulation rates of QAM with some hardcoded stuff (off the top of my head, QAM 64 5/6, QAM 256 3/4 and QAM 256 5/6), which for me led to a high packet loss. Because of this I never really took the time to properly implement this, and I removed the hardcoded implementation before creating this repository.

Implementing these two things would actually be a good addition! 

As far as the PPDU goes, the S1G_1M format is actually really similar to the HT-mixed format if you closely compare the two. It should be pretty compatible.
